//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.239
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWSSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWSSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_arrow {
            get {
                object obj = ResourceManager.GetObject("DMB_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_arrow_s {
            get {
                object obj = ResourceManager.GetObject("DMB_arrow_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_arrowDown {
            get {
                object obj = ResourceManager.GetObject("DMB_arrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_arrowUp {
            get {
                object obj = ResourceManager.GetObject("DMB_arrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_bar {
            get {
                object obj = ResourceManager.GetObject("DMB_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_bg {
            get {
                object obj = ResourceManager.GetObject("DMB_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_blank {
            get {
                object obj = ResourceManager.GetObject("DMB_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_cancel {
            get {
                object obj = ResourceManager.GetObject("DMB_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_controlList {
            get {
                object obj = ResourceManager.GetObject("DMB_controlList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_delete {
            get {
                object obj = ResourceManager.GetObject("DMB_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_deleteAll {
            get {
                object obj = ResourceManager.GetObject("DMB_deleteAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_addMap {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_addMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_Bg {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_Bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_control {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_frame {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_groupControl {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_groupControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_groupInfo {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_groupInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_groupSelect {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_groupSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_receiverAdd {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_receiverAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_receiverControl {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_receiverControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_receiverSelect {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_receiverSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_regionSelect {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_regionSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_SoundControl {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_SoundControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_textControl {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_textControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_dialogue_weatherSelect {
            get {
                object obj = ResourceManager.GetObject("DMB_dialogue_weatherSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_glass {
            get {
                object obj = ResourceManager.GetObject("DMB_glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_group {
            get {
                object obj = ResourceManager.GetObject("DMB_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DMB_ICO_caution {
            get {
                object obj = ResourceManager.GetObject("DMB_ICO_caution", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon DMB_ICO_send {
            get {
                object obj = ResourceManager.GetObject("DMB_ICO_send", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_infoBg {
            get {
                object obj = ResourceManager.GetObject("DMB_infoBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_loading {
            get {
                object obj = ResourceManager.GetObject("DMB_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_loadingBg {
            get {
                object obj = ResourceManager.GetObject("DMB_loadingBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login {
            get {
                object obj = ResourceManager.GetObject("DMB_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_broadcastin {
            get {
                object obj = ResourceManager.GetObject("DMB_login_broadcastin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_caution {
            get {
                object obj = ResourceManager.GetObject("DMB_login_caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_connection {
            get {
                object obj = ResourceManager.GetObject("DMB_login_connection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_dbms {
            get {
                object obj = ResourceManager.GetObject("DMB_login_dbms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_DMBcontrol {
            get {
                object obj = ResourceManager.GetObject("DMB_login_DMBcontrol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_login_terminalControl {
            get {
                object obj = ResourceManager.GetObject("DMB_login_terminalControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_Bar {
            get {
                object obj = ResourceManager.GetObject("DMB_main_Bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_caution {
            get {
                object obj = ResourceManager.GetObject("DMB_main_caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_cautionDefenceList {
            get {
                object obj = ResourceManager.GetObject("DMB_main_cautionDefenceList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_cautionDMBList {
            get {
                object obj = ResourceManager.GetObject("DMB_main_cautionDMBList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_CautionHistory {
            get {
                object obj = ResourceManager.GetObject("DMB_main_CautionHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_cautionList {
            get {
                object obj = ResourceManager.GetObject("DMB_main_cautionList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_control {
            get {
                object obj = ResourceManager.GetObject("DMB_main_control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_documentView {
            get {
                object obj = ResourceManager.GetObject("DMB_main_documentView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_eventLog {
            get {
                object obj = ResourceManager.GetObject("DMB_main_eventLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_history {
            get {
                object obj = ResourceManager.GetObject("DMB_main_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_main {
            get {
                object obj = ResourceManager.GetObject("DMB_main_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_monitoring {
            get {
                object obj = ResourceManager.GetObject("DMB_main_monitoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_receiver {
            get {
                object obj = ResourceManager.GetObject("DMB_main_receiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_receiverView {
            get {
                object obj = ResourceManager.GetObject("DMB_main_receiverView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_regionSave {
            get {
                object obj = ResourceManager.GetObject("DMB_main_regionSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_regionStatistics {
            get {
                object obj = ResourceManager.GetObject("DMB_main_regionStatistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_main_weatherStatistics {
            get {
                object obj = ResourceManager.GetObject("DMB_main_weatherStatistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_minibarOff {
            get {
                object obj = ResourceManager.GetObject("DMB_minibarOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_minibarOn {
            get {
                object obj = ResourceManager.GetObject("DMB_minibarOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_play {
            get {
                object obj = ResourceManager.GetObject("DMB_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiver {
            get {
                object obj = ResourceManager.GetObject("DMB_receiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverError {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverError_G {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverError_G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverGroup {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMa {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMaMonitorError {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMaMonitorError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMaMonitorOk {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMaMonitorOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMaMonitorQ {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMaMonitorQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMonitorError {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMonitorError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMonitorOk {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMonitorOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverMonitorQ {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverMonitorQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverOk {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverRequest {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverRequest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverYu {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverYu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverYuMonitorError {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverYuMonitorError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverYuMonitorOk {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverYuMonitorOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_receiverYuMonitorQ {
            get {
                object obj = ResourceManager.GetObject("DMB_receiverYuMonitorQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_region {
            get {
                object obj = ResourceManager.GetObject("DMB_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_region_blank {
            get {
                object obj = ResourceManager.GetObject("DMB_region_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_region2 {
            get {
                object obj = ResourceManager.GetObject("DMB_region2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_regionGroup {
            get {
                object obj = ResourceManager.GetObject("DMB_regionGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_reset {
            get {
                object obj = ResourceManager.GetObject("DMB_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_selectAll {
            get {
                object obj = ResourceManager.GetObject("DMB_selectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_send {
            get {
                object obj = ResourceManager.GetObject("DMB_send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_send_caution {
            get {
                object obj = ResourceManager.GetObject("DMB_send_caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_send_part2 {
            get {
                object obj = ResourceManager.GetObject("DMB_send_part2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_sendEnd {
            get {
                object obj = ResourceManager.GetObject("DMB_sendEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_sendIng {
            get {
                object obj = ResourceManager.GetObject("DMB_sendIng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_server {
            get {
                object obj = ResourceManager.GetObject("DMB_server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_specialBt {
            get {
                object obj = ResourceManager.GetObject("DMB_specialBt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_specialBtRed {
            get {
                object obj = ResourceManager.GetObject("DMB_specialBtRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_stop {
            get {
                object obj = ResourceManager.GetObject("DMB_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_sub_Bar {
            get {
                object obj = ResourceManager.GetObject("DMB_sub_Bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_subsub_Bar {
            get {
                object obj = ResourceManager.GetObject("DMB_subsub_Bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_system_Gray_44 {
            get {
                object obj = ResourceManager.GetObject("DMB_system_Gray_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemGreen {
            get {
                object obj = ResourceManager.GetObject("DMB_systemGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemGreen_12 {
            get {
                object obj = ResourceManager.GetObject("DMB_systemGreen_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemGreen_44 {
            get {
                object obj = ResourceManager.GetObject("DMB_systemGreen_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemOrange {
            get {
                object obj = ResourceManager.GetObject("DMB_systemOrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemOrange_12 {
            get {
                object obj = ResourceManager.GetObject("DMB_systemOrange_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemRed {
            get {
                object obj = ResourceManager.GetObject("DMB_systemRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemRed_12 {
            get {
                object obj = ResourceManager.GetObject("DMB_systemRed_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemRed_44 {
            get {
                object obj = ResourceManager.GetObject("DMB_systemRed_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_systemWhite {
            get {
                object obj = ResourceManager.GetObject("DMB_systemWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_text {
            get {
                object obj = ResourceManager.GetObject("DMB_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_text_cbs {
            get {
                object obj = ResourceManager.GetObject("DMB_text_cbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_text_tts {
            get {
                object obj = ResourceManager.GetObject("DMB_text_tts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_textbox {
            get {
                object obj = ResourceManager.GetObject("DMB_textbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_Bar {
            get {
                object obj = ResourceManager.GetObject("DMB_title_Bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_broadcasting {
            get {
                object obj = ResourceManager.GetObject("DMB_title_broadcasting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_caution {
            get {
                object obj = ResourceManager.GetObject("DMB_title_caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_connection {
            get {
                object obj = ResourceManager.GetObject("DMB_title_connection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_dbms {
            get {
                object obj = ResourceManager.GetObject("DMB_title_dbms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_DMBcontrol {
            get {
                object obj = ResourceManager.GetObject("DMB_title_DMBcontrol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_history {
            get {
                object obj = ResourceManager.GetObject("DMB_title_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_statistics {
            get {
                object obj = ResourceManager.GetObject("DMB_title_statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_title_terminalControl {
            get {
                object obj = ResourceManager.GetObject("DMB_title_terminalControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DMB_weather {
            get {
                object obj = ResourceManager.GetObject("DMB_weather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
